UnitType.create("a", "Fighter", {attack: 50, attackBonus: 5, capture: 1, cost: 15, defense: 5, grave: "k", hitpoints: 100, rangeMax: 1, rangeMin: 1, repair: true, tileX: 0});
UnitType.create("b", "Archer", {attack: 45, attackBeforeMove: true, attackBonus: 10, capture: 1, cost: 25, defense: 5, grave: "k", hitpoints: 100, rangeMax: 3, rangeMin: 1, tileX: 1});
UnitType.create("c", "Elemental", {attack: 40, attackBonus: 10, cost: 30, defense: 10, hitpoints: 100, rangeMax: 1, rangeMin: 1, tileX: 2});
UnitType.create("d", "Sorceress", {attack: 30, attackBonus: 5, cost: 40, defense: 5, grave: "k", hitpoints: 100, raise: true, rangeMax: 2, rangeMin: 1, tileX: 3});
UnitType.create("e", "Wisp", {attack: 35, attackBonus: 10, berzerk: 5, bless: 2, cost: 50, defense: 10, firstStrike: true, hitpoints: 100, movement: 6, rangeMax: 1, rangeMin: 1, tileX: 4});
UnitType.create("f", "Wolf", {attack: 60, attackBonus: 15, bash: 15, cost: 60, defense: 15, firstStrike: true, hitpoints: 100, movement: 12, rangeMax: 1, rangeMin: 1, tileX: 5});
UnitType.create("g", "Golem", {attack: 60, attackBeforeMove: true, attackBonus: 20, bash: 25, cost: 60, defense: 30, hitpoints: 100, rangeMax: 1, rangeMin: 1, tileX: 6});
UnitType.create("h", "Catapult", {attack: 50, attackBeforeMove: true, attackBonus: 30, attackOrMove: true, cost: 70, defense: 10, demolish: true, explosive: 20, hitpoints: 100, movement: 4, rangeMax: 4, rangeMin: 3, tileX: 7});
UnitType.create("i", "Dragon", {attack: 70, attackBonus: 20, bash: 40, cost: 100, defense: 25, demolish: true, explosive: 10, firstStrike: true, hitpoints: 100, rangeMax: 3, rangeMin: 1, tileX: 8});
UnitType.create("j", "King", {attack: 55, attackBonus: 15, berzerk: 10, bless: 5, capture: 2, defense: 20, grave: "k", hitpoints: 100, rangeMax: 1, rangeMin: 1, tileX: 9});
UnitType.create("k", "Skeleton", {attack: 40, attackBonus: 10, capture: 1, defense: 2, hitpoints: 100, rangeMax: 1, rangeMin: 1, tileX: 10, undead: true});

Terrain.create("m", "Bridge", {category: "r", movement: 2, tileX: 3, tileY: 0});
Terrain.create("n", "Bridge", {category: "r", movement: 2, tileX: 4, tileY: 0});
Terrain.create("6", "Castle", {capture: 2, category: "b", defense: 5, factory: true, heal: 30, movement: 3, player: "blue", tileX: 6, tileY: 3});
Terrain.create("7", "Castle", {capture: 2, category: "b", defense: 5, factory: true, heal: 30, movement: 3, player: "red", tileX: 7, tileY: 3});
Terrain.create("8", "Castle", {capture: 2, category: "b", defense: 5, factory: true, heal: 30, movement: 3, player: "green", tileX: 8, tileY: 3});
Terrain.create("9", "Castle", {capture: 2, category: "b", defense: 5, factory: true, heal: 30, movement: 3, player: "black", tileX: 9, tileY: 3});
Terrain.create("o", "Castle", {capture: 2, category: "b", defense: 5, heal: 30, movement: 3, tileX: 10, tileY: 3});
Terrain.create("b", "Forest", {category: "f", defense: 2, movement: 3, tileX: 10, tileY: 0});
Terrain.create("c", "Forest", {category: "f", defense: 1, movement: 3, tileX: 10, tileY: 1});
Terrain.create("q", "Fort", {category: "b", defense: 4, heal: 10, movement: 3, tileX: 8, tileY: 1});
Terrain.create("d", "Hills", {category: "b", defense: 2, movement: 2, tileX: 9, tileY: 1});
Terrain.create("10", "House", {capture: 1, category: "b", defense: 3, demolish: "s", movement: 3, tileX: 5, tileY: 3});
Terrain.create("11", "House", {capture: 1, category: "b", defense: 3, demolish: "s", heal: 15, income: 10, movement: 3, player: "blue", tileX: 1, tileY: 3});
Terrain.create("12", "House", {capture: 1, category: "b", defense: 3, demolish: "s", heal: 15, income: 10, movement: 3, player: "red", tileX: 2, tileY: 3});
Terrain.create("13", "House", {capture: 1, category: "b", defense: 3, demolish: "s", heal: 15, income: 10, movement: 3, player: "green", tileX: 3, tileY: 3});
Terrain.create("14", "House", {capture: 1, category: "b", defense: 3, demolish: "s", heal: 15, income: 10, movement: 3, player: "black", tileX: 4, tileY: 3});
Terrain.create("e", "Mountain", {category: "m", movement: 4, tileX: 9, tileY: 0});
Terrain.create("f", "Road", {category: "r", movement: 2, tileX: 1, tileY: 1});
Terrain.create("g", "Road", {category: "r", movement: 2, tileX: 2, tileY: 1});
Terrain.create("h", "Road", {category: "r", movement: 2, tileX: 1, tileY: 2});
Terrain.create("i", "Road", {category: "r", movement: 2, tileX: 2, tileY: 2});
Terrain.create("j", "Road", {category: "r", movement: 2, tileX: 0, tileY: 1});
Terrain.create("k", "Road", {category: "r", movement: 2, tileX: 0, tileY: 2});
Terrain.create("l", "Road", {category: "r", movement: 2, tileX: 0, tileY: 3});
Terrain.create("s", "Ruins", {category: "b", defense: 2, movement: 3, repair: "10", tileX: 8, tileY: 0});
Terrain.create("a", "Snow", {movement: 2, tileX: 6, tileY: 1});
Terrain.create("p", "Temple", {category: "b", defense: 3, heal: 25, movement: 3, tileX: 8, tileY: 2});
Terrain.create("0", "Water", {category: "w", tileX: 7, tileY: 1});
Terrain.create("1", "Water", {category: "w", tileX: 3, tileY: 2});
Terrain.create("2", "Water", {category: "w", tileX: 4, tileY: 2});
Terrain.create("3", "Water", {category: "w", tileX: 5, tileY: 2});
Terrain.create("4", "Water", {category: "w", tileX: 6, tileY: 2});
Terrain.create("5", "Water", {category: "w", tileX: 7, tileY: 2});
Terrain.create("r", "Water", {category: "w", tileX: 0, tileY: 0});
Terrain.create("t", "Water", {category: "w", tileX: 2, tileY: 0});
Terrain.create("u", "Water", {category: "w", tileX: 5, tileY: 0});
Terrain.create("v", "Water", {category: "w", tileX: 6, tileY: 0});
Terrain.create("w", "Water", {category: "w", tileX: 7, tileY: 0});
Terrain.create("x", "Water", {category: "w", tileX: 3, tileY: 1});
Terrain.create("y", "Water", {category: "w", tileX: 4, tileY: 1});
Terrain.create("z", "Water", {category: "w", tileX: 5, tileY: 1});
